name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: syo093c/metrics@c430d64381c6a71db703b73ed27412ed641337d1
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: syo093c
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tokyo
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
